### ISSUE TITLE
Error after npm start

### ISSUE THREAD

**Issue by JMarshallst** [dante4rt/blum-airdrop-bot#4]
(node:13236) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (D:\clone\blum-airdrop-bot\node_modules\axios\dist\node\axios.cjs:2015:12)
    at IncomingMessage.handleStreamEnd (D:\clone\blum-airdrop-bot\node_modules\axios\dist\node\axios.cjs:3131:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at Axios.request (D:\clone\blum-airdrop-bot\node_modules\axios\dist\node\axios.cjs:4262:41)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getToken (D:\clone\blum-airdrop-bot\src\api.js:4:20)
    at async D:\clone\blum-airdrop-bot\index.js:51:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by GTIMaster** [comment]
🎮 Your chances to play the game: 0

🏰 Your tribe details:
🚨 Tribe not found!
Join HCA Tribe here: https://t.me/HappyCuanAirdrop/19694

Which feature would you like to use?
1. Claim Farm Reward ≡ƒî╛
2. Start Farming Session ≡ƒÜ£
3. Auto Complete Tasks Γ£à
4. Auto Play and Claim Game Points ≡ƒÄ«
5. Claim Daily Reward Γ£¿
Choose 1, 2, 3, 4, or 5:
🚫 Invalid choice! Please restart the program and choose a valid option.   error show how I can solve this

**Comment by sabbir69x** [comment]
i'm also facing this same error.

**Comment by olisfav** [comment]
Save the file that carries query_id with just .env and the bot should start running.

**Comment by GTIMaster** [comment]
Run at once every task not giving choice update it
